---
# BLUE = current production, image:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue
  labels:
    app: hello-bg
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-bg
      color: blue
  template:
    metadata:
      labels:
        app: hello-bg
        color: blue
        version: v1
    spec:
      containers:
        - name: hello
          image: gcr.io/google-samples/hello-app:1.0
          ports: [{ containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 2
          resources:
            requests: { cpu: 10m, memory: 16Mi }
            limits:   { cpu: 100m, memory: 64Mi }
