apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: url-shortener
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    # EDIT THIS: replace with your fork URL
    repoURL: https://github.com/YOUR-ORG/Devops-learning.git
    targetRevision: main
    path: 08-projects/03-gitops-with-argocd/k8s/overlays/staging
    kustomize:
      images:
        - url-shortener-api=ghcr.io/YOUR-ORG/url-shortener-api:v1.0.0

  destination:
    server: https://kubernetes.default.svc
    namespace: api-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
