apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-required-labels
      match:
        any:
          - resources:
              kinds: [Pod, Deployment, StatefulSet]
      validate:
        message: "Labels 'app.kubernetes.io/name' and 'owner' are required."
        pattern:
          metadata:
            labels:
              app.kubernetes.io/name: "?*"
              owner: "?*"
