apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
    platform.vantapay.io/tier: bootstrap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform

  source:
    repoURL: https://github.com/vantapay/platform-gitops
    targetRevision: main
    path: platform/argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas   # managed by HPA
